# Generated by Django 4.2.7 on 2025-11-18 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_message', models.TextField()),
                ('bot_response', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Chat Message',
                'verbose_name_plural': 'Chat Messages',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='NgrokConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Ngrok LLM API', help_text='Tên cấu hình', max_length=255)),
                ('ngrok_api_url', models.URLField(help_text='URL Ngrok đầy đủ (vd: https://abc123.ngrok-free.app/ask)', verbose_name='Ngrok API URL')),
                ('is_active', models.BooleanField(default=True, help_text='Kích hoạt cấu hình này')),
                ('description', models.TextField(blank=True, help_text='Mô tả về cấu hình này')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Ngrok Configuration',
                'verbose_name_plural': 'Ngrok Configurations',
                'ordering': ['-is_active', '-updated_at'],
            },
        ),
    ]
