# Generated by Django 4.2.7 on 2025-11-18 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='icon_image',
            field=models.ImageField(blank=True, null=True, upload_to='category_icons/', verbose_name='Icon Image'),
        ),
    ]
