# Generated by Django 4.2.7 on 2025-11-18 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_category_icon_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='icon',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Icon Emoji (tùy chọn)'),
        ),
        migrations.AlterField(
            model_name='category',
            name='icon_image',
            field=models.ImageField(null=True, upload_to='category_icons/', verbose_name='Icon Image (bắt buộc)'),
        ),
    ]
