# Generated by Django 4.2.7 on 2025-11-18 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_category_icon_alter_category_icon_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('DEBUG', 'Debug'), ('INFO', 'Info'), ('WARNING', 'Warning'), ('ERROR', 'Error'), ('CRITICAL', 'Critical')], default='INFO', max_length=10, verbose_name='Mức độ')),
                ('logger_name', models.CharField(default='django', max_length=255, verbose_name='Tên logger')),
                ('message', models.TextField(verbose_name='Nội dung log')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Thời gian')),
            ],
            options={
                'verbose_name': 'System Log',
                'verbose_name_plural': 'System Logs',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['-timestamp'], name='blog_system_timesta_170bb4_idx'), models.Index(fields=['level'], name='blog_system_level_ce7e42_idx')],
            },
        ),
    ]
