# Generated by Django 4.2.7 on 2025-12-13 05:35

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(max_length=255, unique=True, verbose_name='Session ID (từ cookie)')),
                ('age', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(16), django.core.validators.MaxValueValidator(120)], verbose_name='Tuổi')),
                ('weight_kg', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(30), django.core.validators.MaxValueValidator(200)], verbose_name='Cân nặng (kg)')),
                ('height_cm', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(100), django.core.validators.MaxValueValidator(250)], verbose_name='Chiều cao (cm)')),
                ('bmi', models.FloatField(blank=True, null=True, verbose_name='BMI')),
                ('tdee', models.FloatField(blank=True, null=True, verbose_name='TDEE (kcal/ngày)')),
                ('goal', models.CharField(blank=True, choices=[('muscle-gain', 'Tăng cơ'), ('fat-loss', 'Giảm cân'), ('strength', 'Tăng sức mạnh'), ('endurance', 'Tăng sức bền'), ('general-health', 'Sức khỏe chung'), ('athletic', 'Thể thao')], max_length=50, null=True, verbose_name='Mục tiêu')),
                ('activity_level', models.CharField(blank=True, choices=[('sedentary', 'Ít vận động (< 1.5 h/tuần)'), ('light', 'Nhẹ (1-3 h/tuần)'), ('moderate', 'Vừa phải (3-5 h/tuần)'), ('active', 'Tích cực (5-6 h/tuần)'), ('intense', 'Cực kỳ tích cực (6-7 h/tuần)')], max_length=50, null=True, verbose_name='Mức độ hoạt động')),
                ('preferred_supplement_types', models.CharField(blank=True, help_text='Phân tách bằng dấu phẩy (ví dụ: whey, creatine, vitamins)', max_length=300, verbose_name='Loại supplement ưa thích')),
                ('dietary_restrictions', models.CharField(blank=True, help_text='Phân tách bằng dấu phẩy (ví dụ: vegan, gluten-free, dairy-free)', max_length=300, verbose_name='Hạn chế chế độ ăn')),
                ('last_activity', models.DateTimeField(auto_now=True, verbose_name='Hoạt động cuối')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
            ],
            options={
                'verbose_name_plural': 'Hồ sơ người dùng',
                'ordering': ['-last_activity'],
                'indexes': [models.Index(fields=['session_id'], name='products_us_session_902e4a_idx')],
            },
        ),
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Tên danh mục')),
                ('slug', models.SlugField(unique=True, verbose_name='URL Slug')),
                ('description', models.TextField(blank=True, verbose_name='Mô tả')),
                ('icon', models.CharField(blank=True, max_length=50, verbose_name='Icon Emoji')),
                ('color', models.CharField(default='#b39ddb', max_length=7, verbose_name='Màu sắc (Hex)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Danh mục sản phẩm',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['slug'], name='products_pr_slug_f060a9_idx')],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Tên sản phẩm')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='URL Slug')),
                ('supplement_type', models.CharField(choices=[('whey', 'Whey Protein'), ('isolate', 'Whey Isolate'), ('concentrate', 'Whey Concentrate'), ('casein', 'Casein Protein'), ('creatine', 'Creatine'), ('preworkout', 'Pre-workout'), ('bcaa', 'BCAA'), ('eaa', 'EAA'), ('vitamins', 'Vitamins'), ('mineral', 'Mineral'), ('fatburner', 'Fat Burner'), ('gainer', 'Weight Gainer'), ('other', 'Khác')], max_length=20, verbose_name='Loại supplement')),
                ('description', models.TextField(verbose_name='Mô tả chi tiết')),
                ('short_description', models.CharField(blank=True, max_length=300, verbose_name='Tóm tắt ngắn')),
                ('image', models.ImageField(upload_to='product_images/', verbose_name='Hình ảnh chính')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Giá (VND)')),
                ('discount_percent', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Giảm giá (%)')),
                ('serving_size', models.CharField(default='30g', max_length=50, verbose_name='Khẩu phần (1 lần dùng)')),
                ('protein_per_serving', models.FloatField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Protein (g)')),
                ('carbs_per_serving', models.FloatField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Carbohydrates (g)')),
                ('fat_per_serving', models.FloatField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Fat (g)')),
                ('calories_per_serving', models.FloatField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Calories (kcal)')),
                ('ingredients', models.TextField(blank=True, verbose_name='Thành phần')),
                ('flavor', models.CharField(blank=True, max_length=100, verbose_name='Hương vị')),
                ('status', models.CharField(choices=[('active', 'Hoạt động'), ('inactive', 'Tạm ngừng'), ('outofstock', 'Hết hàng')], default='active', max_length=20, verbose_name='Trạng thái')),
                ('stock', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Số lượng tồn kho')),
                ('tags', models.CharField(blank=True, help_text='Phân tách bằng dấu phẩy (ví dụ: muscle-gain, lean, vegan)', max_length=300, verbose_name='Tags')),
                ('suitable_for_goals', models.CharField(blank=True, help_text='Phân tách bằng dấu phẩy (ví dụ: muscle-gain, fat-loss, strength)', max_length=300, verbose_name='Phù hợp cho mục tiêu')),
                ('embedding_vector', models.JSONField(blank=True, null=True, verbose_name='Vector embedding (từ LLM)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Cập nhật lúc')),
                ('seo_title', models.CharField(blank=True, max_length=255, verbose_name='SEO Title')),
                ('seo_description', models.CharField(blank=True, max_length=255, verbose_name='SEO Description')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='products.productcategory', verbose_name='Danh mục')),
            ],
            options={
                'verbose_name_plural': 'Sản phẩm',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RecommendationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recommendation_type', models.CharField(choices=[('content-based', 'Content-based (product similarity)'), ('goal-based', 'Goal-based (by user goal)'), ('collaborative', 'Collaborative (similar users)'), ('llm-based', 'LLM-based (AI analysis)'), ('trending', 'Trending (popular)'), ('user-view', 'User view (tracking)')], max_length=50, verbose_name='Loại recommendation')),
                ('score', models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)], verbose_name='Điểm confidence (0-1)')),
                ('reason', models.TextField(blank=True, verbose_name='Lý do gợi ý')),
                ('clicked', models.BooleanField(default=False, verbose_name='Clicked?')),
                ('purchased', models.BooleanField(default=False, verbose_name='Purchased?')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày gợi ý')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Cập nhật lúc')),
                ('recommended_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendation_logs', to='products.product', verbose_name='Sản phẩm gợi ý')),
                ('user_profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recommendation_logs', to='products.userprofile', verbose_name='Hồ sơ người dùng')),
            ],
            options={
                'verbose_name_plural': 'Recommendation Logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user_profile', '-created_at'], name='products_re_user_pr_72a5c2_idx'), models.Index(fields=['recommendation_type'], name='products_re_recomme_25104b_idx'), models.Index(fields=['purchased'], name='products_re_purchas_0ba408_idx')],
            },
        ),
        migrations.CreateModel(
            name='ProductReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_name', models.CharField(max_length=100, verbose_name='Tên người review')),
                ('author_email', models.EmailField(max_length=254, verbose_name='Email')),
                ('rating', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Đánh giá (1-5 sao)')),
                ('title', models.CharField(max_length=200, verbose_name='Tiêu đề review')),
                ('content', models.TextField(verbose_name='Nội dung review')),
                ('is_verified_purchase', models.BooleanField(default=False, verbose_name='Mua xác minh?')),
                ('is_approved', models.BooleanField(default=False, verbose_name='Được phê duyệt?')),
                ('helpful_count', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Số người tìm hữu ích')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày review')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Cập nhật lúc')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='products.product', verbose_name='Sản phẩm')),
            ],
            options={
                'verbose_name_plural': 'Review sản phẩm',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['product', '-rating'], name='products_pr_product_33b0fa_idx'), models.Index(fields=['-created_at'], name='products_pr_created_cdd17c_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['slug'], name='products_pr_slug_3edc0c_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['status'], name='products_pr_status_041708_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['supplement_type'], name='products_pr_supplem_9fa0dc_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['-created_at'], name='products_pr_created_bce1a7_idx'),
        ),
    ]
