# Generated by Django 4.2.7 on 2025-12-13 10:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_productcategory_icon'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductFlavor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flavor', models.CharField(max_length=100, verbose_name='Tên hương vị')),
                ('is_available', models.BooleanField(default=True, verbose_name='Còn hàng')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flavors', to='products.product', verbose_name='Sản phẩm')),
            ],
            options={
                'verbose_name_plural': 'Hương vị sản phẩm',
                'ordering': ['product', 'flavor'],
                'indexes': [models.Index(fields=['product', 'flavor'], name='products_pr_product_cb75c9_idx')],
                'unique_together': {('product', 'flavor')},
            },
        ),
    ]
