# Generated by Django 4.2.7 on 2026-01-04 08:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0005_userprofile_user_alter_userprofile_session_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='PasswordResetToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=255, unique=True, verbose_name='Token Reset')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Thời gian tạo')),
                ('expires_at', models.DateTimeField(verbose_name='Hết hạn lúc')),
                ('is_used', models.BooleanField(default=False, verbose_name='Đã sử dụng')),
                ('used_at', models.DateTimeField(blank=True, null=True, verbose_name='Thời gian sử dụng')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='password_reset_tokens', to=settings.AUTH_USER_MODEL, verbose_name='Người dùng')),
            ],
            options={
                'verbose_name_plural': 'Mã Reset Mật Khẩu',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['token'], name='products_pa_token_a39a16_idx'), models.Index(fields=['user', 'is_used'], name='products_pa_user_id_e2e4d1_idx'), models.Index(fields=['expires_at'], name='products_pa_expires_9a5d19_idx')],
            },
        ),
    ]
