# Generated by Django 4.2.7 on 2026-01-06 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_productreview_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='suitable_for_goals',
            field=models.CharField(blank=True, help_text='Phân tách bằng dấu phẩy (ví dụ: muscle-gain, weight-gain, fat-loss, strength, recovery, maintenance, free-lactose, whey-protein,...)', max_length=300, verbose_name='Phù hợp cho mục tiêu'),
        ),
        migrations.AlterField(
            model_name='product',
            name='supplement_type',
            field=models.CharField(choices=[('whey', 'Whey Protein'), ('isolate', 'Whey Isolate'), ('hydrolyzed', 'Whey Hydrolyzed'), ('concentrate', 'Whey Concentrate'), ('mass', 'Mass Gainer'), ('casein', 'Casein Protein'), ('creatine', 'Creatine'), ('preworkout', 'Pre-workout'), ('bcaa', 'BCAA'), ('eaa', 'EAA'), ('vitamins', 'Vitamins'), ('mineral', 'Mineral'), ('fatburner', 'Fat Burner'), ('gainer', 'Weight Gainer'), ('other', 'Khác')], max_length=20, verbose_name='Loại supplement'),
        ),
        migrations.AlterField(
            model_name='product',
            name='tags',
            field=models.CharField(blank=True, help_text='Phân tách bằng dấu phẩy (ví dụ: muscle-gain,weight-gain,lean, vegan,... )', max_length=300, verbose_name='Tags'),
        ),
        migrations.AlterField(
            model_name='recommendationlog',
            name='recommendation_type',
            field=models.CharField(choices=[('personalized', 'Personalized (by user profile)'), ('content-based', 'Content-based (product similarity)'), ('goal-based', 'Goal-based (by user goal)'), ('collaborative', 'Collaborative (similar users)'), ('llm-based', 'LLM-based (AI analysis)'), ('trending', 'Trending (popular)'), ('user-view', 'User view (tracking)')], max_length=50, verbose_name='Loại recommendation'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='goal',
            field=models.CharField(blank=True, choices=[('muscle-gain', 'Tăng cơ'), ('fat-loss', 'Giảm cân'), ('strength', 'Tăng sức mạnh'), ('endurance', 'Tăng sức bền'), ('body-recomposition', 'Vừa tăng cơ vừa giảm mỡ'), ('maintenance', 'Duy trì thể trạng'), ('general-health', 'Sức khỏe chung'), ('athletic', 'Thể thao')], max_length=50, null=True, verbose_name='Mục tiêu'),
        ),
    ]
