# Generated by Django 4.2.7 on 2026-01-21 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_alter_product_suitable_for_goals_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='recommendationlog',
            constraint=models.UniqueConstraint(fields=('user_profile', 'recommended_product', 'recommendation_type'), name='unique_user_product_rec_type'),
        ),
    ]
