# Generated by Django 4.2.7 on 2026-01-21 05:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_recommendationlog_unique_user_product_rec_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('product_view', 'Product viewed'), ('product_click', 'Product clicked'), ('review_submit', 'Review submitted'), ('review_helpful', 'Review marked helpful'), ('rec_shown', 'Recommendation shown to user'), ('rec_clicked', 'Recommendation clicked'), ('rec_purchased', 'Recommended product purchased'), ('search', 'Search performed'), ('filter_apply', 'Filter applied'), ('sort_applied', 'Sort applied'), ('login', 'User logged in'), ('logout', 'User logged out'), ('register', 'User registered'), ('profile_setup', 'Profile setup completed'), ('profile_update', 'Profile updated'), ('page_load', 'Page loaded'), ('api_call', 'API called')], db_index=True, max_length=30, verbose_name='Loại event')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text="Thông tin thêm: {'page': '...', 'from_rec': '...', 'score': ...}", verbose_name='Metadata (JSON)')),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Thời gian')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='events', to='products.product', verbose_name='Sản phẩm')),
                ('user_profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='events', to='products.userprofile', verbose_name='Hồ sơ người dùng')),
            ],
            options={
                'verbose_name_plural': 'Event Logs',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.DeleteModel(
            name='RecommendationLog',
        ),
        migrations.AddIndex(
            model_name='eventlog',
            index=models.Index(fields=['user_profile', '-timestamp'], name='products_ev_user_pr_2f4f95_idx'),
        ),
        migrations.AddIndex(
            model_name='eventlog',
            index=models.Index(fields=['event_type', '-timestamp'], name='products_ev_event_t_00e540_idx'),
        ),
        migrations.AddIndex(
            model_name='eventlog',
            index=models.Index(fields=['product', '-timestamp'], name='products_ev_product_174b2b_idx'),
        ),
        migrations.AddIndex(
            model_name='eventlog',
            index=models.Index(fields=['-timestamp'], name='products_ev_timesta_2d5966_idx'),
        ),
    ]
